DROP TABLE AGENDA ;
DROP TABLE ACCION ;
DROP TABLE TODO  ;
DROP TABLE HISTORIAL ;
DROP TABLE CAJERO ;
DROP TABLE NOTIFICACION  ;



DROP TABLE USUARIO ;
-- DROP TABLE GRUPO ;
--  DROP TABLE GRUPOUSUARIO ;
DROP TABLE GRUPOACCION ;
DROP TABLE ACCION ;
DROP TABLE ACCIONRECIENTE ;
DROP TABLE ESTADO ;
DROP TABLE GRUPOESTADO ;

DROP TABLE MES ;
DROP TABLE EMAILCONFIGURATION ;
DROP TABLE TOKEN ;
DROP TABLE AGENDA ;
DROP TABLE AGENDAHISTORIAL ;

DROP TABLE BANCO ;
DROP TABLE PARAMETROS;