/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  avbravo
 * Created: 08/19/2021
 */




/**
BANCO
**/



INSERT INTO BANCO (BANCO, SIGLAS, DESCRIPCION, ESCONTROL,ACTIVO,ORDEN) VALUES ('TELERED','TELERED','REGISTRO DE CONTROL','SI','SI',1);
INSERT INTO BANCO (BANCO, SIGLAS, DESCRIPCION, ESCONTROL,ACTIVO,ORDEN) VALUES ('BANCO NACIONAL DE PANAMA','BNP','BANCO NACIONAL DE PANAMA','NO','SI',2);
INSERT INTO BANCO (BANCO, SIGLAS, DESCRIPCION, ESCONTROL,ACTIVO,ORDEN) VALUES ('BANCO GENERAL','BGENERAL','BANCO GENERAL','NO','SI',3);

/**
CAJERO
**/
INSERT INTO CAJERO ( CAJERO, BANCOID, DESCRIPCION, DIRECCION, DIRECCIONCORTA, ACTIVO, ORDEN) 
            VALUES ('1245',2,'CAJERO', 'CALLE 50, PANAKMA','CALLE 50','SI',1);
INSERT INTO CAJERO ( CAJERO, BANCOID, DESCRIPCION, DIRECCION, DIRECCIONCORTA, ACTIVO, ORDEN) 
            VALUES ('4578',2,'CAJERO', 'VIA BRASIL, PANAKMA','VIA BRASIL','SI',1);
INSERT INTO CAJERO ( CAJERO, BANCOID, DESCRIPCION, DIRECCION, DIRECCIONCORTA, ACTIVO, ORDEN) 
            VALUES ('8025',2,'CAJERO', 'EL DORADOR, PANAKMA','EL DORADO','SI',1);
INSERT INTO CAJERO (CAJERO, BANCOID, DESCRIPCION, DIRECCION, DIRECCIONCORTA, ACTIVO, ORDEN) 
            VALUES ('3679',3,'CAJERO', 'VIA ESPAÑA, PANAKMA','VIA ESPAÑA','SI',1);


/*
==============================================================================
*/





/**
*GRUPO 
*/

INSERT INTO GRUPO ( GRUPO,DESCRIPCION, ACTIVO, ORDEN)  VALUES ( 'ADMIN', 'ADMINISTRADOR','SI',1);
INSERT INTO GRUPO ( GRUPO,DESCRIPCION,ACTIVO, ORDEN)  VALUES ('TELERED','USUARIO DE TELERED','SI',2);
INSERT INTO GRUPO ( GRUPO,DESCRIPCION, ACTIVO,ORDEN)  VALUES ('BANCO', 'USUARIO DE BANCO','SI',3);


/**
USUARIO
*/
INSERT INTO USUARIO (USERNAME ,PASSWORD,NOMBRE,CEDULA , EMAIL , TELEFONO , CELULAR,  BANCOID ,ACTIVO, ORDEN)
     VALUES( 'telered','W6agfy8ygJaWwsWZZf7wrg==','aristides villarreal', '7-7-7','avbravo@gmail.com','a','a', 1,'SI',1);

INSERT INTO USUARIO (USERNAME ,PASSWORD,NOMBRE,CEDULA , EMAIL , TELEFONO , CELULAR,  BANCOID ,ACTIVO, ORDEN)
       VALUES('bnp','ihzFsJRCzKMluA0cDr9DZQ==','bnp user', '6-7-7','avbravo@gmail.com','b','b',2,'SI',1);

INSERT INTO USUARIO (USERNAME ,PASSWORD,NOMBRE,CEDULA , EMAIL , TELEFONO , CELULAR,  BANCOID ,ACTIVO, ORDEN)
       VALUES('bgeneral','WGs3xzpDZay18NAOW2wSGQ==','bgenearl user', '8-7-7','avbravo@gmail.com','g','g',3,'SI',1);




/**
*GRUPOUSUARIO
*/

INSERT INTO GRUPOUSUARIO ( USUARIOID , GRUPOID,ACTIVO) VALUES ( 1,  1,'SI');
INSERT INTO GRUPOUSUARIO ( USUARIOID , GRUPOID,ACTIVO) VALUES ( 1, 2,'SI');
INSERT INTO GRUPOUSUARIO ( USUARIOID , GRUPOID,ACTIVO) VALUES (1, 3,'SI');
INSERT INTO GRUPOUSUARIO ( USUARIOID , GRUPOID,ACTIVO) VALUES (2, 3,'SI');
INSERT INTO GRUPOUSUARIO ( USUARIOID , GRUPOID,ACTIVO) VALUES (3, 3,'SI');


-- /*
-- =============================================================================
-- */
-- /*
-- ACCION
-- */





/**
EMAILCONFIGURATION
*/
INSERT INTO EMAILCONFIGURATION ( EMAIL, PASSWORD,MAILSMTPHOST ,MAILSMTPAUTH , MAILSMTPPORT , MAILSMTPSTARTTLSENABLE,  ACTIVO, ORDEN)
       VALUES('avillarreal@people-inmotion.com' ,'0HlHHe9wdvaQS1UEA/ZOgg==', 'smtp.office365.com','true','587','true','SI',1);


/**

GRUPOESTADO
Agrupa los estados para mostrar los totales en el Dashboard
*/

INSERT INTO  GRUPOESTADO (GRUPOESTADO, ACTIVO, ORDEN) VALUES( 'Solicitado','SI',1);
INSERT INTO  GRUPOESTADO (GRUPOESTADO, ACTIVO, ORDEN) VALUES('En Proceso','SI',2);
INSERT INTO  GRUPOESTADO (GRUPOESTADO, ACTIVO, ORDEN) VALUES('Finalizado','SI',3);
INSERT INTO  GRUPOESTADO (GRUPOESTADO, ACTIVO, ORDEN) VALUES('No se puede ejecutar','SI',4);


/**

ESTADO
*/
INSERT INTO  ESTADO   (ESTADO, GRUPOESTADOID,PREDETERMINADO,ACTIVO , 	ORDEN) VALUES ( 'En espera de ejecucion', 1, 'SI','SI',1);
INSERT INTO  ESTADO   (ESTADO, GRUPOESTADOID,PREDETERMINADO,ACTIVO , 	ORDEN) VALUES ( 'Procesando', 2, 'NO','SI',1);
INSERT INTO  ESTADO   (ESTADO, GRUPOESTADOID,PREDETERMINADO,ACTIVO ,	ORDEN) VALUES ('Ejecutada',3, 'NO' ,'SI',2);
INSERT INTO  ESTADO   (ESTADO, GRUPOESTADOID,PREDETERMINADO,ACTIVO ,	ORDEN) VALUES ('Acción no se puede ejecutar(Solo en caso de duplicados)',4, 'NO' , 'SI',3);
INSERT INTO  ESTADO   (ESTADO, GRUPOESTADOID,PREDETERMINADO,ACTIVO ,	ORDEN) VALUES ('Robot no disponible',3, 'NO' ,'SI',4);


/*
GRUPOACCION
*/

INSERT INTO GRUPOACCION  (GRUPOACCION ,ACTIVO,	ORDEN) VALUES('Bajar Plantilla','SI',1); 
INSERT INTO GRUPOACCION  (GRUPOACCION ,ACTIVO,	ORDEN) VALUES('Reinicio Remoto','SI',2); 
INSERT INTO GRUPOACCION  (GRUPOACCION ,ACTIVO,	ORDEN) VALUES('Encender (Subir Plantilla)','SI',3); 

/*
===========================================================================
*/

/*
ACCION
<REINICIO REMOTO SE CREAN DESDE EL MODULO BANCO>
<BAJAR PLANTILLA>: LAS SOLITICA EL BANCO CON UN VALOR PREDETERKINADO 
                 : TAMBIEN LAS CREA LOS TECNICOS CON OTROS VALORES QUE NO SON EL PREDETERMINADO
<Encender (Subir Plantilla> : LAS CREA EL BANCO CON  VALOR PREDETERMINADO           
*/
/*
REINICIO REMOTO
*/
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN) VALUES( 'Fuera de Servicio Red/Problema Tecnico', 2, 'NO','SI',1);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Fuera de Servicio Red/Error en la lectora/Atasco de Tarjeta', 2, 'NO','SI',2);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Falla de comunbicación Banco', 2, 'NO','SI',3);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('+3 Opciones en menu de razon reinicio (SIG)', 2, 'NO','SI',4);



/*
BAJAR PLANTILLA
*/
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Mantenimiento cambio Password de usuario',  1, 'NO','SI',5);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Mantenimiento Eliminación de  usuario',  1, 'NO','SI',6);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Mantenimiento Reemplazo de Hardware',  1, 'NO','SI',7);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Mantenimiento de Software o Servicio',  1, 'NO','SI',8);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Extracción de Logs',  1, 'NO','SI',9);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Reinstalacion',  1, 'NO','SI',10);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Bajar plantilla y habilitar puertos USB',  1, 'SI','SI',11);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Bajar plantilla y mantener puertos USB bloqueados',  1, 'SI','SI',11);
INSERT INTO ACCION (  ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Habilitar puertos USB y mantener plantilla activa',  1, 'SI','SI',11);

/*
ENCENDER SUBIR PLANTILLA
*/
INSERT INTO ACCION ( ACCION, GRUPOACCIONID ,PREDETERMINADO,ACTIVO ,ORDEN)  VALUES('Encender Subir Plantilla', 3, 'SI','SI',12);



/*
===========================================================================
*/
/*
MES
*/
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES (  'ENERO',1,'SI',1); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'FEBRERO',2,'SI',2); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'MARZO',3,'SI',3); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'ABRIL',4,'SI',4); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ('MAYO',5,'SI',5); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'JUNIO',6,'SI',6); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'JULIO',7,'SI',7); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'AGOSTO',8,'SI',8); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'SEPTIEMBRE',9,'SI',9); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'OCTUBRE',10,'SI',10); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'NOVIEMBRE',11,'SI',11); 
INSERT INTO MES (MES , NUMERO, ACTIVO,ORDEN) VALUES ( 'DICIEMBRE',12,'SI',12); 

	   